### PR TITLE
Article: Looking for long-term maintainers around the Embulk eco-system

### PR DESCRIPTION
**Pull request by dmikurube**

### CODE REVIEW

**Comment by dmikurube** [comment]
@hiroyuki-sato @hito4t This would be a new article under `embulk.org`. I referred your names (that are public in your GitHub profiles) in this article draft. Please check this just in case.

**Comment by hiroyuki-sato** [comment]
@dmikurube I read half of the article. I'll review it next week.

**Comment by dmikurube** [comment]
Thanks! Then, I'll update the date of the article accordingly.

**Review by hiroyuki-sato — APPROVED** [review]
LGTM👍

**Comment by dmikurube** [comment]
Made some trivial wording fixes, and updated the date. Let me publish this!

@hito4t If you're concerned about referring your name here, please let us know. We'll remove that part in that case.

**Pull request merged**
